### PR TITLE
Improve GitHub integration

### PR DESCRIPTION
**Pull request by stweil**
* Use the full license text (generated using GitHub). Now GitHub can automatically detect and show the license in the information bar of the repository.

* Enhance and format the README, so it is more informative on GitHub. Change the text as suggested by Shree Devi Kumar.

### CODE REVIEW

**Comment by stweil** [comment]
@Shreeshrii, please review.

**Comment by stweil** [comment]
I considered to add "LSTM" but thought that it was to technical for the README. The wiki offers more room for details and explanations.

**Comment by amitdo** [comment]
Putting the license info in a file named 'COPYING' is GNU-style.
https://www.gnu.org/prep/standards/html_node/Releases.html

Putting the license info in a file named 'LICENSE' is Apache-style.
https://github.com/apache

Tesseract itself currently uses both 'LICENSE' and  'COPYING'.

**Comment by stweil** [comment]
I rebased the commits and now use `LICENSE` instead of `COPYING`. Thank you, @amitdo, for the hint.

**Pull request merged**
